# Generated by Django 5.2.13 on 2026-06-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_alter_usuario_email_unique_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='etiqueta',
            field=models.CharField(choices=[('Problema', 'Problema'), ('Solicitação', 'Solicitação'), ('Computador Locado', 'Computador Locado'), ('Impressora Locada', 'Impressora Locada'), ('Bug', 'Bug')], default='Problema', max_length=30, verbose_name='Etiqueta'),
        ),
    ]
