# Generated by Django 5.2.13 on 2026-06-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0004_chamado_atendente_fechamento_chamado_data_reabertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='etiqueta',
            field=models.CharField(blank=True, choices=[('Problema', 'Problema'), ('Solicitação', 'Solicitação'), ('Computador Locado', 'Computador Locado'), ('Impressora Locada', 'Impressora Locada'), ('Bug', 'Bug')], default='Problema', max_length=30, null=True, verbose_name='Etiqueta'),
        ),
    ]
