# Generated by Django 5.2.13 on 2026-07-03 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0007_seed_etiquetas_fixas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoMultimidia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=100, verbose_name='Setor')),
                ('local', models.CharField(max_length=200, verbose_name='Local / Sala')),
                ('sala', models.CharField(blank=True, max_length=100, verbose_name='Sala')),
                ('data', models.DateField(verbose_name='Data do Agendamento')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Fim')),
                ('equipamentos', models.JSONField(default=list, verbose_name='Equipamentos Necessários')),
                ('finalidade', models.CharField(blank=True, max_length=300, verbose_name='Finalidade')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Recusado', 'Recusado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Agendamento de Multimídia',
                'verbose_name_plural': 'Agendamentos de Multimídia',
                'ordering': ['-data', 'horario_inicio'],
            },
        ),
    ]
