# Generated by Django 5.2.13 on 2026-08-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0008_add_agendamento_multimidia'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentomultimidia',
            name='google_event_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ID do Evento no Google Calendar'),
        ),
        migrations.AlterField(
            model_name='agendamentomultimidia',
            name='local',
            field=models.CharField(choices=[('Auditório da Prefeitura', 'Auditório da Prefeitura'), ('Sede da Secretaria de Saúde', 'Sede da Secretaria de Saúde'), ('Centro Integrado', 'Centro Integrado'), ('Faetec', 'Faetec'), ('Sicoob', 'Sicoob'), ('Ciep', 'Ciep'), ('Maristas', 'Maristas'), ('Cipec', 'Cipec'), ('Sala dos Conselhos', 'Sala dos Conselhos')], max_length=200, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='agendamentomultimidia',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Recusado', 'Recusado'), ('Cancelado', 'Cancelado'), ('Concluído', 'Concluído')], default='Pendente', max_length=10, verbose_name='Status'),
        ),
    ]
